server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/uniclub
    username: root
    password: bao123
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  private-key: BwI1vCFQv+jpMf9SDukFtZDNPPOEhLczr3eZREiwCig=