server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/uniclub
    username: root
    password: bao123
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  private-key: OO2dNrWwfX9kQHnyUwrVsdL3Qi0MgvYE/KW3aUDD5DU=

path:
  save-file: /Users/thienbao/Documents/upload

redis:
  host: localhost
  port: 6379